[build]
  command = "make netlify"
  publish = ""
  functions = "functions"
[build.environment]
  GOBIN = "/opt/build/repo/functions"
[template.environment]
  GO_IMPORT_PATH = "github.com/leonhfr/honeybadger-bot"
[context.production.environment]
  LICHESS_ID = "honeybadger-bot"
