name: Deploy to Raspberry Pi
on:
  push:
    branches: [ master ]
  # Allows the workflow to be run manually and to be triggered by another repository
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download latest honeybadger binary
        run: |
          cd /home/ubuntu/lichess-bot/engines_test
          curl -s https://api.github.com/repos/leonhfr/honeybadger/releases/latest \
            | jq -r '.assets[] | select(.name | contains("Linux_arm64")) | .browser_download_url' \
            | xargs -I % curl -L % > honeybadger.tar.gz

      - name: Stopping bot service
        run: sudo systemctl stop bot.service

      - name: Replace engine binary
        run: |
          cd /home/ubuntu/lichess-bot/engines_test
          tar -xvvf honeybadger.tar.gz
          rm honeybadger.tar.gz

      - name: Starting bot service
        run: sudo systemctl start bot.service
