name: generate rating graph

on:
  schedule:
    - cron: 0 2 * * *

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      LICHESS_ID: turkjs
      OUTPUT: dist/rating-graph.png

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: install dependencies
        run: |
          pip install -r graph/requirements.txt

      - name: generate graph
        run: |
          python ./graph/graph.py
      # graph will be available at https://raw.githubusercontent.com/leonhfr/honeybadger-bot/output/rating-graph.png
      - name: push graph to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
